plugins:
  - serverless-offline

service: challengecrudaws

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::*"

functions:
  upload:
    handler: controllers.user.profile.upload
  environment:
    bucket: UInstantSolution
    events:
      - s3:
        bucket: UInstantSolution
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/
          - suffix: .jpg
      - s3:
        bucket: UInstantSolution
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/
          - suffix: .jpeg
      - s3:
        bucket: UInstantSolution
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/
          - suffix: .png
          
